server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # we also could use this to split
        # CRUD operations to different microservices
        # here we choose GET only for [users] MS
        #- Method=GET

      - id: Users
        service: UserManagementService
        uri: lb://UserManagementService
        predicates:
        - Path=/api/users/**
        filters:
        - StripPrefix=2
        - PrefixPath=/v1/users

      - id: Roles
        service: UserManagementService
        uri: lb://UserManagementService
        predicates:
        - Path=/api/roles/**
        filters:
        - StripPrefix=2
        - PrefixPath=/v1/roles

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.cloud.consul: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

# changing Spring Actuator base path
management:
  endpoints:
    web:
      base-path: /status
      exposure:
        include: '*'
